import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');
await page.getByPlaceholder('Ваше имя').fill('Combat QA');
await page.getByRole('button',{name:'Создать бункер',exact:true}).click();
await page.locator('.card').first().click();
await page.evaluate(()=>window.__net.send({k:'settings',s:{combatTurnTime:40}}));
await page.getByRole('button',{name:'⚔ Тестовая арена',exact:true}).click();
await page.waitForFunction(()=>window.__game?.combat?.active);
await page.waitForTimeout(700);
await page.screenshot({path:'artifacts/combat-planning.png'});
await page.locator('.combat-action').filter({hasText:'Укрыться'}).click();
await page.waitForFunction(()=>window.__game.combat.plan.some(a=>a.t==='hunker'));
await page.getByRole('button',{name:'Отменить последний шаг'}).click();
await page.waitForFunction(()=>window.__game.combat.plan.length===0);
const me=await page.evaluate(()=>window.__game.combat.myUnit());
console.log('UNIT',JSON.stringify(me));
await page.locator('.combat-action').filter({hasText:'Движение'}).click();
const point=await page.evaluate(()=>{const combat=window.__game.combat,u=combat.myUnit();const [x,y]=combat.pos(u.col+1,u.floor);return combat.site.toScreen(x,y+.6)});
await page.mouse.click(point[0],point[1]);
await page.waitForFunction(()=>window.__game.combat.plan.some(a=>a.t==='move'));
await page.locator('.combat-action').filter({hasText:'Ещё'}).click();
await page.screenshot({path:'artifacts/combat-plan-queued.png'});
const round=await page.evaluate(()=>window.__game.combat.cs.round);
await page.getByRole('button',{name:/Завершить план/}).click();
await page.waitForFunction(r=>window.__game.combat.cs.phase==='anim'||window.__game.combat.cs.round>r,round,{timeout:45000});
await page.screenshot({path:'artifacts/combat-resolution.png'});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/combat-mobile.png'});
const report={arenaStarted:true,defendQueued:true,undo:true,movementQueued:true,planCommitted:true,errors};
await fs.writeFile('artifacts/combat-qa.json',JSON.stringify(report,null,2));
console.log(report);
await browser.close();
